[package]
name       = "mako_core"
version    = "0.1.0"
edition    = "2021"
repository = "https://github.com/umijs/mako"
license    = "MIT"

[dependencies]
tokio = { version = "1", features = ["full"] }
swc_core = { workspace= true, features = [
  "__ecma",
  "__visit",
  "__utils",
  "__ecma_transforms",
  "__parser",
  "ecma_ast",
  "__ecma_plugin_transform",
  "ecma_codegen",
  "ecma_quote",
  "ecma_minifier",
  "common_concurrent",
  "common_tty",
  "common_sourcemap",
  "ecma_minifier_concurrent",
  "ecma_transforms_react",
  "ecma_transforms_module",
  "ecma_transforms_optimization",
  "ecma_transforms_proposal",
  "ecma_transforms_typescript",
  "ecma_transforms_compat",
  "__testing_transform",
  "ecma_visit_path",
  "ecma_preset_env",
  "css_ast",
  "css_codegen",
  "css_parser",
  "css_utils",
  "css_visit",
  "css_visit_path",
  "css_minifier",
  "css_compat",
  "css_modules",
  "css_prefixer",
  "base_node",
] }

swc_error_reporters = "0.16.1"
swc_node_comments   = "0.19.1"
swc_emotion         = "0.51.0"

base64                = "0.21.2"
petgraph              = "0.6.3"
md5                   = "0.7.0"
serde                 = { workspace = true }
serde_json            = { workspace = true }
config                = "0.13.3"
nodejs-resolver       = "0.0.88"
rayon                 = "1.7.0"
thiserror             = "1.0.43"
tracing               = "0.1.37"
tracing-subscriber    = { version = "0.3.17", features = ["env-filter"] }
notify                = { version = "6.1.1", default-features = false, features = ["macos_kqueue"] }
notify-debouncer-full = { version = "0.3.1", default-features = false }
futures               = "0.3.28"
fs_extra              = "1.3.0"
glob                  = "0.3.1"
clap                  = { version = "4.3.11", features = ["derive"] }
pathdiff              = "0.2.1"
anyhow                = "1.0.71"
hyper                 = { version = "0.14.27", features = ["full"] }
tungstenite           = "0.19.0"
tokio-tungstenite     = "0.19.0"
hyper-tungstenite     = "0.10.0"
hyper-staticfile      = "0.9.5"
mime_guess            = "2.0.4"
twox-hash             = "1.6.3"
toml                  = "0.7.6"
serde_yaml            = "0.9.22"
serde-xml-rs          = "0.6.0"
svgr-rs               = "0.1.3"
cached                = { workspace = true }
colored               = "2"
mdxjs                 = "0.1.14"
regex                 = "1.9.3"
indexmap              = "2.0.0"
eframe                = { version = "0.22.0", optional = true }
puffin                = { version = "0.16.0", optional = true }
puffin_egui           = { version = "0.22.0", optional = true }
lazy_static           = "1.4.0"
convert_case          = "0.6.0"
path-clean            = "1.0.1"
sailfish              = "0.8.3"
merge-source-map      = "1.2.0"

[features]
profile = ["dep:eframe", "dep:puffin", "dep:puffin_egui"]
